// Generated by CoffeeScript 1.9.2
(function() {
  var ElmCompiler, exec, join;

  exec = require('child_process').exec;

  join = require('path').join;

  module.exports = ElmCompiler = (function() {
    ElmCompiler.prototype.brunchPlugin = true;

    ElmCompiler.prototype.type = 'javascript';

    ElmCompiler.prototype.extension = 'elm';

    function ElmCompiler(config) {
      var ref, ref1, ref2;
      this.config = config;
      this.main = (ref = this.config.plugins.elmBrunch) != null ? ref.main : void 0;
      this.compileTo = (ref1 = (ref2 = this.config.plugins.elmBrunch) != null ? ref2.compileTo : void 0) != null ? ref1 : join(this.config.paths["public"], 'js', 'elm.js');
    }

    ElmCompiler.prototype.compile = function(data, path, callback) {
      var ref, src;
      src = (ref = this.main) != null ? ref : path;
      return exec('elm make --yes --output ' + this.compileTo + ' ' + src, function(error, stdout, stderr) {
        return callback(error, error ? stderr : null);
      });
    };

    return ElmCompiler;

  })();

}).call(this);
