// Generated by CoffeeScript 1.9.2
(function() {
  var ElmCompiler, exec, join;

  exec = require('child_process').exec;

  join = require('path').join;

  module.exports = ElmCompiler = (function() {
    ElmCompiler.prototype.brunchPlugin = true;

    ElmCompiler.prototype.type = 'javascript';

    ElmCompiler.prototype.extension = 'elm';

    function ElmCompiler(config) {
      var ref, ref1;
      this.config = config;
      this.outputDir = (ref = (ref1 = this.config.plugins.elmBrunch) != null ? ref1.outputDir : void 0) != null ? ref : join(this.config.paths["public"], 'js');
    }

    ElmCompiler.prototype.compile = function(data, path, callback) {
      return exec('elm make --yes --output ' + join(this.outputDir, 'elm.js') + ' ' + path, function(error, stdout, stderr) {
        return callback(error, error ? stderr : null);
      });
    };

    return ElmCompiler;

  })();

}).call(this);
